### PR TITLE
Displaying the list of users with pink for girls, blue for boys

### PR DESCRIPTION
**Pull request by Madriix**
I first tried to create a plugin, but without success. I thought it would be quicker to do it directly in the source.

### CODE REVIEW

**Comment by TehPeGaSuS** [comment]
IMHO, this isn't something that should be in the source code.

Here's why:
- Not everyone uses a IRC client that have a predefined `ASL` of sorts nor everyone specify `M` or `F` on their realname to tell what their gender is.
- The `M` or `F` can be part of a **true** name, like `John F Kennedy`, etc.
- What about the other people, like the **LGBTQIA+** community?

So, IMHO, this should be a third party plugin as it doesn't enhance the webpanel usability.

Cheers

**Comment by ValwareIRC** [comment]
Hi there, thanks for the PR. @TehPeGaSuS is right, this seems to follow a very specific syntax in a very specific placement that it not standard or even common, so should be a third-party plugin since it's third-party behavior.
Additionally, if something like this were to be included, I would like the configurable options regarding gender labels and coloring.

As for writing your own plugin, you can check the ["example_plugin"](https://github.com/unrealircd/unrealircd-webpanel-plugins/tree/main/example_plugin) to get started.

Instead of using the `HOOKTYPE_NAVBAR`, I would change to `HOOKTYPE_PRE_FOOTER` (or `HOOKTYPE_HEADER` with a `defer`), and from there you can insert your own custom javascript:

```
class example_plugin
{
	/* You must specify these here for internal use
 	 * All of these are mandatory or your plugin will not work.
 	*/
	public $name = "example_plugin"; // Name of your plugin
	public $author = "You"; // Name or handle of your lovely self
	public $version = "1.0"; // Version of this plugin
	public $description = "An example plugin to show how to make stuff"; // Description of your beautiful plugin
	public $email = "you@example.org"; // An email people can contact you with in case of problems

	/** This is run on plugin load. You can add hooks and initialize whatever databases
 	 * that you think you might need.
   	*/
	function __construct()
	{
		Hook::func(HOOKTYPE_PRE_FOOTER, 'example_plugin::pre_footer'); 
	}

	/** This is the method (function) that we have hooked.
 	 * Now we can do things. Make sure to check the relevant hooks
    	 * for the right variables to use.
 	 * We use variable reference (&) on this hook
   	*/
	public static function pre_footer(&$pages)
	{
		?>
			<script>

				// check we're on the right page
				if (!window.location.pathname.endsWith('users/index.php')
					return;

				// grab the table by id attribute
				const table = document.getElementById('data_list');

				// the rest of your code
				/* insert hacks here */

			</script>
		<?php
	}
}
```

**Comment by Madriix** [comment]
@ValwareIRC I can't seem to call this in the main function of a plugin:

`$users = $rpc->user()->getAll();`

It always shows this error because `$rpc `is not recognized:
`Fatal error: Uncaught Error: Call to a member function user() on null`


The currently non-functional plugin:

```
<?php

class asl
{
    public $name = "asl";
    public $author = "Madrix";
    public $version = "1.0";
    public $description = "An example plugin to show how to make stuff";
    public $email = "";

    function __construct()
    {
        Hook::func(HOOKTYPE_PRE_FOOTER, 'asl::pre_footer');
    }

    public static function pre_footer(&$pages)
    {

        $css = "";

?>
        <script>
            // check we're on the right page
            if (window.location.pathname.endsWith('users/') || window.location.pathname.endsWith('users/index.php')) {
                // grab the table by id attribute
                //const table = document.getElementById('data_list');

                <?php
                    GLOBAL $rpc;
                    /* Get the user list */
                    $users = $rpc->user()->getAll();
                
                    $code = "";
                    foreach($users as $user)
                    {
                        if (preg_match("/^[0-9]{2}\/F\//i", $user->user->realname))
                        $code .= '$(\'.usertable table tbody tr[value="'.$user->name.'"]\').addClass("girl");';
                        else if (preg_match("/^[0-9]{2}\/H\//i", $user->user->realname))
                        $code .= '$(\'.usertable table tbody tr[value="'.$user->name.'"]\').addClass("boy");';

                    }
                    
                    $css = `<style>
                    tr.boy {
                        color: #0667ff;
                    }
                    tr.girl {
                        color: #ff00ef;
                    }
                    </style>`;

                    echo $code;

                ?>

                // the rest of your code
                /* insert hacks here */
            }
        </script>

        <?=$css;?>
<?php
    }
}
?>
```

**Comment by ValwareIRC** [comment]
@Madriix, indeed, as I said, you should make the modifications to the page in JavaScript from there, instead of PHP. Unfortunately there isn't a PHP-ish hook that gets called on a users table, so you can't edit that information before it's displayed by using PHP. You'll have to edit it after the fact, using JavaScript.

**Comment by Madriix** [comment]
@ValwareIRC 
It seems to be functional now:
```
<?php

class NickColorASL
{
    public $name = "NickColorASL";
    public $author = "Madrix";
    public $version = "1.0";
    public $description = "Allows displaying the list of usernames with pink for girls, blue for boys, and black for others. It also displays the real name in the link's title attribute";
    public $email = "";

    function __construct()
    {
        Hook::func(HOOKTYPE_PRE_FOOTER, 'NickColorASL::pre_footer');
    }

    public static function pre_footer(&$pages)
    {

        $css = '<style>
        #data_list .boy {
            color: #0667ff;
        }
        #data_list .girl {
            color: #ff00ef;
        }
        </style>';;

?>
        <script>
            function Timer() {
                if (window.location.pathname.endsWith('users/') || window.location.pathname.endsWith('users/index.php')) {
                    //const table = document.getElementById('data_list');

                    <?php
                    require_once(UPATH . "/inc/connection.php");
                    global $rpc;
                    $users = $rpc->user()->getAll();

                    $code = "";
                    foreach ($users as $user) {
                        $user_name = $user->name;
                        // Check girls [FG]
                        // F = Femme (french)
                        // F = Fille (french)
                        // F = Female (english)
                        // G = Girl (english)
                        if (preg_match("/^[0-9]{2}[\/\s][FG]/i", $user->user->realname)) {
                            $code .= 'var links = document.querySelectorAll("#data_list tbody tr td.sorting_1 a");
                            links.forEach(function(link) {
                                if (link.textContent === "' . $user_name . '") {
                                    link.classList.add("girl");
                                    link.setAttribute("title", "' . $user->user->realname . '");
                                }
                            });';

                        // Check boys [HBM]
                        // H = Homme (french)
                        // M = Mec (french)
                        // B = Boy (english)
                        // M = Male (english)
                        } else if (preg_match("/^[0-9]{2}[\/\s][HBM]/i", $user->user->realname)) {
                            $code .= 'var links = document.querySelectorAll("#data_list tbody tr td.sorting_1 a");
                            links.forEach(function(link) {
                                if (link.textContent === "' . $user_name . '") {
                                    link.classList.add("boy");
                                    link.setAttribute("title", "' . $user->user->realname . '");
                                }
                            });';
                        } else {
                            $code .= 'var links = document.querySelectorAll("#data_list tbody tr td.sorting_1 a");
                            links.forEach(function(link) {
                                if (link.textContent === "' . $user_name . '") {
                                    link.setAttribute("title", "' . $user->user->realname . '");
                                }
                            });';  
                        }
                    }

                    echo $code;

                    ?>
                }
            }

            // UX issue: it checks every 1 second because otherwise it won't refresh when selecting by country.
           setInterval(() => {
                if (args.ajax) {
                    Timer()
                }
            }, 2000);
        </script>

        <?= $css; ?>
<?php
    }
}
?>
```

**Comment by Madriix** [comment]
I updated it and added the statistics as follows:

> Showing 1 to 100 of 415 entries [females: 95] [males: 273] [others: 47] [ipv4: 297] [ipv6: 101]

```
<?php

class NickColorASL
{
    public $name = "NickColorASL";
    public $author = "Madrix";
    public $version = "1.0";
    public $description = "Allows displaying the list of usernames with pink for girls, blue for boys, and black for others. It also displays the real name in the link's title attribute";
    public $email = "";

    function __construct()
    {
        Hook::func(HOOKTYPE_PRE_FOOTER, 'NickColorASL::pre_footer');
    }

    public static function pre_footer(&$pages)
    {

        require_once(UPATH . "/inc/connection.php");
        global $rpc;
        $users = $rpc->user()->getAll();

        $css = '<style>
        #data_list .boy {
            color: #0667ff;
        }
        #data_list .girl {
            color: #ff00ef;
        }
        </style>';;

?>
        <script>
            var connectedUserStatistics = {
                users: 0,
                girls: 0,
                boys: 0,
                others: 0,
                ipv4: 0,
                ipv6: 0
            };

            var data_list_info_html = "";
            var first = true;

            function Timer(first) {
                if (window.location.pathname.endsWith('users/') || window.location.pathname.endsWith('users/index.php')) {
                    //const table = document.getElementById('data_list');

                    <?php
                    $code = "connectedUserStatistics = {
                        users: 0,
                        girls: 0,
                        boys: 0,
                        others: 0,
                        ipv4: 0,
                        ipv6: 0
                    };";
                    $code .= 'if(first) data_list_info_html = document.querySelector("#data_list_info").innerHTML;';
                    echo $code;
                    foreach ($users as $user) {
                        $user_name = $user->name;
                        $code .= 'connectedUserStatistics.users++;';
                        if ($user->ip != null && preg_match("/:/i", $user->ip)) {
                            $code .= 'if(first) connectedUserStatistics.ipv6++;';
                        } else if ($user->ip != null) {
                            $code .= 'if(first) connectedUserStatistics.ipv4++;';
                        }
                        // Check girls [FG]
                        // F = Femme (french)
                        // F = Fille (french)
                        // F = Female (english)
                        // G = Girl (english)
                        if (preg_match("/^[0-9]{2}[\/\s][FG]/i", $user->user->realname)) {
                            $code .= 'var links = document.querySelectorAll("#data_list tbody tr td.sorting_1 a");
                            links.forEach(function(link) {
                                if (link.textContent === "' . $user_name . '") {
                                    link.classList.add("girl");
                                    link.setAttribute("title", "' . $user->user->realname . '");
                                }
                            });
                            connectedUserStatistics.girls++;';

                        // Check boys [HBM]
                        // H = Homme (french)
                        // M = Mec (french)
                        // B = Boy (english)
                        // M = Male (english)
                        } else if (preg_match("/^[0-9]{2}[\/\s][HBM]/i", $user->user->realname)) {
                            $code .= 'var links = document.querySelectorAll("#data_list tbody tr td.sorting_1 a");
                            links.forEach(function(link) {
                                if (link.textContent === "' . $user_name . '") {
                                    link.classList.add("boy");
                                    link.setAttribute("title", "' . $user->user->realname . '");
                                }
                            });
                            connectedUserStatistics.boys++;';
                        } else {
                            $code .= 'var links = document.querySelectorAll("#data_list tbody tr td.sorting_1 a");
                            links.forEach(function(link) {
                                if (link.textContent === "' . $user_name . '") {
                                    link.setAttribute("title", "' . $user->user->realname . '");
                                }
                            });
                            connectedUserStatistics.others++;';  
                        }
                    }

                    $code .= 'if(first) { document.querySelector("#data_list_info").innerHTML = data_list_info_html + " [females: "+connectedUserStatistics.girls+"] [males: "+connectedUserStatistics.boys+"] [others: "+connectedUserStatistics.others+"] [ipv4: "+connectedUserStatistics.ipv4+"] [ipv6: "+connectedUserStatistics.ipv6+"]"; }';
                    echo $code;

                    ?>
                }
            }

            // UX issue: it checks every 1 second because otherwise it won't refresh when selecting by country.
           setInterval(() => {
                if (!!document.querySelector("#data_list").querySelector("tbody")) {
                    Timer(first)
                    first=false
                }
            }, 2000);
        </script>

        <?= $css; ?>
<?php
    }
}
?>
```

**Comment by ValwareIRC** [comment]
if it works, see how the other plugins are structured and make a PR to the [plugins repo](/unrealircd/unrealircd-webpanel-plugins)

**Pull request closed without merging**
